name: Release management
on:
    push:
        branches:
            - master
jobs:
    update-draft-release:
        runs-on: ubuntu-latest
        steps:
            - name: Release Drafter
              uses: toolmantim/release-drafter@v5.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

